// Copyright 2018 The go-exactonline AUTHORS. All rights reserved.
//
// Use of this source code is governed by a MIT
// license that can be found in the LICENSE file.
// Code generated by gen-services.go; DO NOT EDIT.
package cashflow

import (
	"context"

	"github.com/mcnijman/go-exactonline/types"
)

// DirectDebitMandatesEndpoint is responsible for communicating with
// the DirectDebitMandates endpoint of the Cashflow service.
type DirectDebitMandatesEndpoint service

// DirectDebitMandates:
// Service: Cashflow
// Entity: DirectDebitMandates
// URL: /api/v1/{division}/cashflow/DirectDebitMandates
// HasWebhook: false
// IsInBeta: false
// Methods: GET POST PUT DELETE
// Endpoint docs: https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=CashflowDirectDebitMandates
type DirectDebitMandates struct {
	// ID: Primary key
	ID *types.GUID `json:"ID,omitempty"`

	// Account: Account to which the mandate belongs.
	Account *types.GUID `json:"Account,omitempty"`

	// BankAccount: Bank account to which the mandate belongs.
	BankAccount *types.GUID `json:"BankAccount,omitempty"`

	// CancellationDate: Date that the mandate is cancelled. Used to check the validity of the mandate.
	CancellationDate *types.Date `json:"CancellationDate,omitempty"`

	// Created: Creation date
	Created *types.Date `json:"Created,omitempty"`

	// Creator: User ID of creator
	Creator *types.GUID `json:"Creator,omitempty"`

	// CreatorFullName: Name of creator
	CreatorFullName *string `json:"CreatorFullName,omitempty"`

	// Description: Displays the description of the mandate.
	Description *string `json:"Description,omitempty"`

	// Division: Division code
	Division *int `json:"Division,omitempty"`

	// FirstSend: Indicates the first collection hasn&#39;t been sent/confirmed with this mandate.
	FirstSend *byte `json:"FirstSend,omitempty"`

	// Main: Indicates if the mandate is the main, you can have only one main mandate
	Main *byte `json:"Main,omitempty"`

	// Modified: Last modified date
	Modified *types.Date `json:"Modified,omitempty"`

	// Modifier: User ID of modifier
	Modifier *types.GUID `json:"Modifier,omitempty"`

	// ModifierFullName: Name of modifier
	ModifierFullName *string `json:"ModifierFullName,omitempty"`

	// PaymentType: Depending on the payment type, a different bank file will be generated. 0 = One-off payment, 1 = Recurrent payment, 2 = AdHoc (UK only)
	PaymentType *int `json:"PaymentType,omitempty"`

	// Reference: Displays a reference number for the mandate. It is a unique reference number that you can assign to each mandate.
	Reference *string `json:"Reference,omitempty"`

	// SignatureDate: Date that the mandate is signed. The collection must take place after the signature date of the mandate. The date is used to check the validity of the mandate.
	SignatureDate *types.Date `json:"SignatureDate,omitempty"`

	// Type: Depending on the type, a different bank file will be generated. 0 = Core, 1 = B2B and 2 = bottomline (UK only)
	Type *int `json:"Type,omitempty"`
}

func (s *DirectDebitMandates) GetIdentifier() types.GUID {
	return *s.ID
}

// List the DirectDebitMandates entities in the provided division.
// If all is true, all the paginated results are fetched; if false, list the first page.
func (s *DirectDebitMandatesEndpoint) List(ctx context.Context, division int, all bool) ([]*DirectDebitMandates, error) {
	var entities []*DirectDebitMandates
	u, err := s.client.ResolvePathWithDivision("/api/v1/{division}/cashflow/DirectDebitMandates?$select=*", division)
	if err != nil {
		return nil, err
	}
	if all {
		err = s.client.ListRequestAndDoAll(ctx, u.String(), &entities)
		return entities, err
	}
	_, _, _, err = s.client.ListRequestAndDo(ctx, u.String(), &entities)
	return entities, err
}
