// Copyright 2018 The go-exactonline AUTHORS. All rights reserved.
//
// Use of this source code is governed by a MIT
// license that can be found in the LICENSE file.
// Code generated by gen-services.go; DO NOT EDIT.
package financial

import (
	"context"

	"github.com/mcnijman/go-exactonline/api"
	"github.com/mcnijman/go-exactonline/types"
)

// GLAccountClassificationMappingsEndpoint is responsible for communicating with
// the GLAccountClassificationMappings endpoint of the Financial service.
type GLAccountClassificationMappingsEndpoint service

// GLAccountClassificationMappings:
// Service: Financial
// Entity: GLAccountClassificationMappings
// URL: /api/v1/beta/{division}/financial/GLAccountClassificationMappings
// HasWebhook: false
// IsInBeta: true
// Methods: GET POST PUT DELETE
// Endpoint docs: https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=FinancialGLAccountClassificationMappings
type GLAccountClassificationMappings struct {
	// ID: Primary key
	ID *types.GUID `json:"ID,omitempty"`

	// Classification: ID of the classification
	Classification *types.GUID `json:"Classification,omitempty"`

	// ClassificationCode: Code of the classification
	ClassificationCode *string `json:"ClassificationCode,omitempty"`

	// ClassificationDescription: Description of the classification
	ClassificationDescription *string `json:"ClassificationDescription,omitempty"`

	// Division: Division of the classification mapping
	Division *int `json:"Division,omitempty"`

	// GLAccount: ID of the general ledger account
	GLAccount *types.GUID `json:"GLAccount,omitempty"`

	// GLAccountCode: Code of the general ledger account
	GLAccountCode *string `json:"GLAccountCode,omitempty"`

	// GLAccountDescription: Description of the general ledger account
	GLAccountDescription *string `json:"GLAccountDescription,omitempty"`

	// GLSchemeCode: Code of the general ledger scheme
	GLSchemeCode *string `json:"GLSchemeCode,omitempty"`

	// GLSchemeDescription: Description of the general ledger scheme
	GLSchemeDescription *string `json:"GLSchemeDescription,omitempty"`

	// GLSchemeID: General ledger scheme ID of the element
	GLSchemeID *types.GUID `json:"GLSchemeID,omitempty"`
}

// List the GLAccountClassificationMappings entities in the provided division.
// If all is true, all the paginated results are fetched; if false, list the first page.
func (s *GLAccountClassificationMappingsEndpoint) List(ctx context.Context, division int, all bool, o *api.ListOptions) ([]*GLAccountClassificationMappings, error) {
	var entities []*GLAccountClassificationMappings
	u, _ := s.client.ResolvePathWithDivision("/api/v1/beta/{division}/financial/GLAccountClassificationMappings", division) // #nosec
	api.AddListOptionsToURL(u, o)

	if all {
		err := s.client.ListRequestAndDoAll(ctx, u.String(), &entities)
		return entities, err
	}
	_, _, _, err := s.client.ListRequestAndDo(ctx, u.String(), &entities)
	return entities, err
}
