// Copyright 2018 The go-exactonline AUTHORS. All rights reserved.
//
// Use of this source code is governed by a MIT
// license that can be found in the LICENSE file.
// Code generated by gen-services.go; DO NOT EDIT.
package financial

import "github.com/mcnijman/go-exactonline/api"

type service struct {
	client *api.Client
}

// FinancialService is responsible for communication with the Financial
// endpoints of the Exact Online API.
type FinancialService struct {
	client *api.Client

	common service // Reuse a single struct instead of allocating one for each service on the heap.

	// Endpoints available under this service
	AgingOverview                   *AgingOverviewEndpoint
	AgingPayablesList               *AgingPayablesListEndpoint
	AgingReceivablesList            *AgingReceivablesListEndpoint
	ExchangeRates                   *ExchangeRatesEndpoint
	FinancialPeriods                *FinancialPeriodsEndpoint
	GLAccountClassificationMappings *GLAccountClassificationMappingsEndpoint
	GLAccounts                      *GLAccountsEndpoint
	GLClassifications               *GLClassificationsEndpoint
	GLSchemes                       *GLSchemesEndpoint
	GLTransactionTypes              *GLTransactionTypesEndpoint
	Journals                        *JournalsEndpoint
	JournalStatusList               *JournalStatusListEndpoint
	OutstandingInvoicesOverview     *OutstandingInvoicesOverviewEndpoint
	PayablesList                    *PayablesListEndpoint
	ProfitLossOverview              *ProfitLossOverviewEndpoint
	ReceivablesList                 *ReceivablesListEndpoint
	ReportingBalance                *ReportingBalanceEndpoint
	Returns                         *ReturnsEndpoint
	RevenueList                     *RevenueListEndpoint
}

// NewFinancialService creates a new initialized instance of the
// FinancialService.
func NewFinancialService(apiClient *api.Client) *FinancialService {
	s := &FinancialService{client: apiClient}

	s.common.client = apiClient

	s.AgingOverview = (*AgingOverviewEndpoint)(&s.common)
	s.AgingPayablesList = (*AgingPayablesListEndpoint)(&s.common)
	s.AgingReceivablesList = (*AgingReceivablesListEndpoint)(&s.common)
	s.ExchangeRates = (*ExchangeRatesEndpoint)(&s.common)
	s.FinancialPeriods = (*FinancialPeriodsEndpoint)(&s.common)
	s.GLAccountClassificationMappings = (*GLAccountClassificationMappingsEndpoint)(&s.common)
	s.GLAccounts = (*GLAccountsEndpoint)(&s.common)
	s.GLClassifications = (*GLClassificationsEndpoint)(&s.common)
	s.GLSchemes = (*GLSchemesEndpoint)(&s.common)
	s.GLTransactionTypes = (*GLTransactionTypesEndpoint)(&s.common)
	s.Journals = (*JournalsEndpoint)(&s.common)
	s.JournalStatusList = (*JournalStatusListEndpoint)(&s.common)
	s.OutstandingInvoicesOverview = (*OutstandingInvoicesOverviewEndpoint)(&s.common)
	s.PayablesList = (*PayablesListEndpoint)(&s.common)
	s.ProfitLossOverview = (*ProfitLossOverviewEndpoint)(&s.common)
	s.ReceivablesList = (*ReceivablesListEndpoint)(&s.common)
	s.ReportingBalance = (*ReportingBalanceEndpoint)(&s.common)
	s.Returns = (*ReturnsEndpoint)(&s.common)
	s.RevenueList = (*RevenueListEndpoint)(&s.common)

	return s
}
