// Copyright 2018 The go-exactonline AUTHORS. All rights reserved.
//
// Use of this source code is governed by a MIT
// license that can be found in the LICENSE file.
// Code generated by gen-services.go; DO NOT EDIT.
package exactonline

import (
	"context"
)

// ActivitiesComplaintsService is responsible for communicating with
// the Complaints endpoint of the Activities service.
type ActivitiesComplaintsService service

// ActivitiesComplaints:
// Service: Activities
// Entity: Complaints
// URL: /api/v1/{division}/activities/Complaints
// HasWebhook: false
// IsInBeta: false
// Methods: GET POST
// Endpoint docs: https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=ActivitiesComplaints
type ActivitiesComplaints struct {
	// ID: The Primary key
	ID *GUID `json:",omitempty"`

	// Account: The account that is related to the complaint
	Account *GUID `json:",omitempty"`

	// AccountName: The name of the account
	AccountName *string `json:",omitempty"`

	// AssignedTo: The user that the complaint is assigned to
	AssignedTo *GUID `json:",omitempty"`

	// AssignedToFullName: The user name
	AssignedToFullName *string `json:",omitempty"`

	// Attachments: Attachments linked to the complaint
	Attachments *[]byte `json:",omitempty"`

	// Complaint: A short description of the complaint
	Complaint *string `json:",omitempty"`

	// Contact: The contact person that is related to the complaint
	Contact *GUID `json:",omitempty"`

	// ContactFullName: The name of the contact person
	ContactFullName *string `json:",omitempty"`

	// Created: Creation date
	Created *Date `json:",omitempty"`

	// Creator: User ID of the creator
	Creator *GUID `json:",omitempty"`

	// CreatorFullName: Name of the creator
	CreatorFullName *string `json:",omitempty"`

	// Division: The division
	Division *int `json:",omitempty"`

	// Document: The document that is linked to the complaint
	Document *GUID `json:",omitempty"`

	// DocumentSubject: The subject of the document
	DocumentSubject *string `json:",omitempty"`

	// HID: The human readable key
	HID *int `json:",omitempty"`

	// Modified: Last modified date
	Modified *Date `json:",omitempty"`

	// Modifier: User ID of the last modifier
	Modifier *GUID `json:",omitempty"`

	// ModifierFullName: Name of the last modifier
	ModifierFullName *string `json:",omitempty"`

	// NextAction: The date indicating by when the next action has to be taken
	NextAction *Date `json:",omitempty"`

	// Notes: The notes of the complaint
	Notes *string `json:",omitempty"`

	// ReceiptDate: The date the complaint was received
	ReceiptDate *Date `json:",omitempty"`

	// Status: Status: 0 = Void, 5 = Rejected, 10 = Draft, 20 = Open, 30 = Approved, 40 = Realized, 50 = Processed
	Status *int `json:",omitempty"`

	// StatusDescription: The description of the status
	StatusDescription *string `json:",omitempty"`
}

func (s *ActivitiesComplaints) GetIdentifier() GUID {
	return *s.ID
}

// List the Complaints entities in the provided divison.
// If all is true, all the paginated results are fetched; if false, list the first page.
func (s *ActivitiesComplaintsService) List(ctx context.Context, division int, all bool) ([]*ActivitiesComplaints, error) {
	var entities []*ActivitiesComplaints
	u, err := s.client.ResolvePathWithDivision("/api/v1/{division}/activities/Complaints?$select=*", division)
	if err != nil {
		return nil, err
	}
	if all {
		err = s.client.ListRequestAndDoAll(ctx, u.String(), &entities)
		return entities, err
	}
	_, _, _, err = s.client.ListRequestAndDo(ctx, u.String(), &entities)
	return entities, err
}
