// Copyright 2018 The go-exactonline AUTHORS. All rights reserved.
//
// Use of this source code is governed by a MIT
// license that can be found in the LICENSE file.
// Code generated by gen-services.go; DO NOT EDIT.
package exactonline

import (
	"context"
)

// ContinuousMonitoringIndicatorDeviatingAmountEnteredsService is responsible for communicating with
// the IndicatorDeviatingAmountEntereds endpoint of the ContinuousMonitoring service.
type ContinuousMonitoringIndicatorDeviatingAmountEnteredsService service

// ContinuousMonitoringIndicatorDeviatingAmountEntereds:
// Service: ContinuousMonitoring
// Entity: IndicatorDeviatingAmountEntereds
// URL: /api/v1/beta/{division}/continuousmonitoring/IndicatorDeviatingAmountEntereds
// HasWebhook: false
// IsInBeta: true
// Methods: GET POST PUT DELETE
// Endpoint docs: https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=ContinuousMonitoringIndicatorDeviatingAmountEntereds
type ContinuousMonitoringIndicatorDeviatingAmountEntereds struct {
	// ID: Primary key
	ID *GUID `json:",omitempty"`

	// Active: Indicates if this indicator is active or inactive
	Active *byte `json:",omitempty"`

	// Classification: Indicator classification (1 = Quality, 2 = Advice). Default = 1
	Classification *int `json:",omitempty"`

	// Created: Creation date
	Created *Date `json:",omitempty"`

	// CreateSignal: Indicates whether a signal is created
	CreateSignal *byte `json:",omitempty"`

	// Creator: User ID of creator
	Creator *GUID `json:",omitempty"`

	// CreatorFullName: Name of creator
	CreatorFullName *string `json:",omitempty"`

	// Description: Description of indicator
	Description *string `json:",omitempty"`

	// Division: Division code
	Division *int `json:",omitempty"`

	// ExternalCode: External code
	ExternalCode *string `json:",omitempty"`

	// IndicatorGLAccounts: Collection of GL accounts
	IndicatorGLAccounts *[]byte `json:",omitempty"`

	// Modified: Last modified date
	Modified *Date `json:",omitempty"`

	// Modifier: User ID of modifier
	Modifier *GUID `json:",omitempty"`

	// ModifierFullName: Name of modifier
	ModifierFullName *string `json:",omitempty"`

	// Operator: Operator to be used in conjunction with journal (1 = Equal to, 2 = Unequal to, 3 = Greater than, 4 = Greater than or equal to, 5 = Less than, 6 = Less than or equal to, 7 = Between)
	Operator *int `json:",omitempty"`

	// Severity: Severity of the indicators (1 = Low, 2 = Medium, 3 = High, 4 = Critical)
	Severity *int `json:",omitempty"`

	// Type: Indicator type (1 = Balance G/L account per financial year, 2 = Usage of journals, 3 = Deviating amount entered, 4 = Liquidity, 5 = VAT Return deadline, 6 = Difference result in percentage, 7 = Different VAT code used)
	Type *int `json:",omitempty"`

	// ValueFrom: Value from/Value. Default value is 0. This field should be used together with any choice of operator.
	ValueFrom *float64 `json:",omitempty"`

	// ValueTo: Value to. Default value is 0.
	ValueTo *float64 `json:",omitempty"`
}

func (s *ContinuousMonitoringIndicatorDeviatingAmountEntereds) GetIdentifier() GUID {
	return *s.ID
}

// List the IndicatorDeviatingAmountEntereds entities in the provided divison.
// If all is true, all the paginated results are fetched; if false, list the first page.
func (s *ContinuousMonitoringIndicatorDeviatingAmountEnteredsService) List(ctx context.Context, division int, all bool) ([]*ContinuousMonitoringIndicatorDeviatingAmountEntereds, error) {
	var entities []*ContinuousMonitoringIndicatorDeviatingAmountEntereds
	u, err := s.client.ResolvePathWithDivision("/api/v1/beta/{division}/continuousmonitoring/IndicatorDeviatingAmountEntereds?$select=*", division)
	if err != nil {
		return nil, err
	}
	if all {
		err = s.client.ListRequestAndDoAll(ctx, u.String(), &entities)
		return entities, err
	}
	_, _, _, err = s.client.ListRequestAndDo(ctx, u.String(), &entities)
	return entities, err
}
