// Copyright 2018 The go-exactonline AUTHORS. All rights reserved.
//
// Use of this source code is governed by a MIT
// license that can be found in the LICENSE file.
// Code generated by gen-services.go; DO NOT EDIT.
package exactonline

import (
	"context"
)

// InventorySerialNumbersService is responsible for communicating with
// the SerialNumbers endpoint of the Inventory service.
type InventorySerialNumbersService service

// InventorySerialNumbers:
// Service: Inventory
// Entity: SerialNumbers
// URL: /api/v1/{division}/inventory/SerialNumbers
// HasWebhook: false
// IsInBeta: false
// Methods: GET
// Endpoint docs: https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=InventorySerialNumbers
type InventorySerialNumbers struct {
	// ID: Primary key
	ID *GUID `json:",omitempty"`

	// Available: Availability of this serial number
	Available *byte `json:",omitempty"`

	// Created: Creation date
	Created *Date `json:",omitempty"`

	// Creator: User ID of creator
	Creator *GUID `json:",omitempty"`

	// CreatorFullName: Name of creator
	CreatorFullName *string `json:",omitempty"`

	// Division: Division code
	Division *int `json:",omitempty"`

	// EndDate: End date of effective period for serial number
	EndDate *Date `json:",omitempty"`

	// IsBlocked: Boolean value indicating whether or not the serial number is blocked
	IsBlocked *byte `json:",omitempty"`

	// Item: Item
	Item *GUID `json:",omitempty"`

	// ItemCode: Item code
	ItemCode *string `json:",omitempty"`

	// ItemDescription: Description of item
	ItemDescription *string `json:",omitempty"`

	// Modified: Last modified date
	Modified *Date `json:",omitempty"`

	// Modifier: User ID of modifier
	Modifier *GUID `json:",omitempty"`

	// ModifierFullName: Name of modifier
	ModifierFullName *string `json:",omitempty"`

	// Remarks: Remarks
	Remarks *string `json:",omitempty"`

	// SerialNumber: Human readable serial number
	SerialNumber *string `json:",omitempty"`

	// StartDate: Start date of effective period for serial number
	StartDate *Date `json:",omitempty"`

	// StorageLocation: ID of storage location where serial number is available
	StorageLocation *GUID `json:",omitempty"`

	// StorageLocationCode: Code of storage location where serial number is available
	StorageLocationCode *string `json:",omitempty"`

	// StorageLocationDescription: Description of storage location where serial number is available
	StorageLocationDescription *string `json:",omitempty"`

	// Warehouse: ID of warehouse where serial number is available
	Warehouse *GUID `json:",omitempty"`

	// WarehouseCode: Code of warehouse where serial number is available
	WarehouseCode *string `json:",omitempty"`

	// WarehouseDescription: Description of warehouse where serial number is available
	WarehouseDescription *string `json:",omitempty"`
}

func (s *InventorySerialNumbers) GetIdentifier() GUID {
	return *s.ID
}

// List the SerialNumbers entities in the provided divison.
// If all is true, all the paginated results are fetched; if false, list the first page.
func (s *InventorySerialNumbersService) List(ctx context.Context, division int, all bool) ([]*InventorySerialNumbers, error) {
	var entities []*InventorySerialNumbers
	u, err := s.client.ResolvePathWithDivision("/api/v1/{division}/inventory/SerialNumbers?$select=*", division)
	if err != nil {
		return nil, err
	}
	if all {
		err = s.client.ListRequestAndDoAll(ctx, u.String(), &entities)
		return entities, err
	}
	_, _, _, err = s.client.ListRequestAndDo(ctx, u.String(), &entities)
	return entities, err
}
