// Copyright 2018 The go-exactonline AUTHORS. All rights reserved.
//
// Use of this source code is governed by a MIT
// license that can be found in the LICENSE file.
// Code generated by gen-services.go; DO NOT EDIT.
package exactonline

import (
	"context"
)

// ManufacturingByProductReceiptsService is responsible for communicating with
// the ByProductReceipts endpoint of the Manufacturing service.
type ManufacturingByProductReceiptsService service

// ManufacturingByProductReceipts:
// Service: Manufacturing
// Entity: ByProductReceipts
// URL: /api/v1/{division}/manufacturing/ByProductReceipts
// HasWebhook: false
// IsInBeta: false
// Methods: GET POST
// Endpoint docs: https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=ManufacturingByProductReceipts
type ManufacturingByProductReceipts struct {
	// StockTransactionId: ID of stock transaction related to this by-product finish
	StockTransactionId *GUID `json:",omitempty"`

	// CreatedBy: ID of creating user
	CreatedBy *GUID `json:",omitempty"`

	// CreatedByFullName: Name of the creating user
	CreatedByFullName *string `json:",omitempty"`

	// CreatedDate: Date this by-product finish was created
	CreatedDate *Date `json:",omitempty"`

	// DraftStockTransactionID: Serial or batch numbers are reserved prior to a POST to ByProductReceipts. This DraftStockTransactionID represents the group of serial or batch numbers to be used in this transaction.
	DraftStockTransactionID *GUID `json:",omitempty"`

	// HasReversibleQuantity: Indicates if this ByProductReceipt has a quantity eligible to be reversed via ByProductReversals
	HasReversibleQuantity *bool `json:",omitempty"`

	// IsBackflush: Boolean indicating if this by-product finish was the result of shop order backflushing
	IsBackflush *bool `json:",omitempty"`

	// IsBatch: Does the ByProductReceipt&#39;s item use batch numbers
	IsBatch *byte `json:",omitempty"`

	// IsFractionAllowedItem: Indicates if fractions (for example 0.35) are allowed for quantities of the ByProductReceipt&#39;s item
	IsFractionAllowedItem *byte `json:",omitempty"`

	// IsSerial: Does the ByProductReceipt&#39;s item use serial numbers
	IsSerial *byte `json:",omitempty"`

	// Item: ID of by-product item
	Item *GUID `json:",omitempty"`

	// ItemCode: Code of by-product item
	ItemCode *string `json:",omitempty"`

	// ItemDescription: Description of by-product item
	ItemDescription *string `json:",omitempty"`

	// ItemPictureUrl: Picture url of by-product item
	ItemPictureUrl *string `json:",omitempty"`

	// Quantity: Quantity of this by-product finish
	Quantity *float64 `json:",omitempty"`

	// ShopOrder: ID of shop order, which produced the by-product
	ShopOrder *GUID `json:",omitempty"`

	// ShopOrderMaterialPlan: ID of the shop order material plan for this by-product
	ShopOrderMaterialPlan *GUID `json:",omitempty"`

	// ShopOrderNumber: Number of shop order, which produced the by-product
	ShopOrderNumber *int `json:",omitempty"`

	// StorageLocation: ID of storage location finished to
	StorageLocation *GUID `json:",omitempty"`

	// StorageLocationCode: Code of storage location finished to
	StorageLocationCode *string `json:",omitempty"`

	// StorageLocationDescription: Description of storage location finished to
	StorageLocationDescription *string `json:",omitempty"`

	// TransactionDate: Effective date of this by-product finish
	TransactionDate *Date `json:",omitempty"`

	// Unit: Unit of measurement abbreviation of by-product item
	Unit *string `json:",omitempty"`

	// UnitDescription: Unit of measurement of by-product item
	UnitDescription *string `json:",omitempty"`

	// Warehouse: ID of warehouse finished to
	Warehouse *GUID `json:",omitempty"`

	// WarehouseCode: Code of warehouse finished to
	WarehouseCode *string `json:",omitempty"`

	// WarehouseDescription: Description of warehouse finished to
	WarehouseDescription *string `json:",omitempty"`
}

func (s *ManufacturingByProductReceipts) GetIdentifier() GUID {
	return *s.StockTransactionId
}

// List the ByProductReceipts entities in the provided divison.
// If all is true, all the paginated results are fetched; if false, list the first page.
func (s *ManufacturingByProductReceiptsService) List(ctx context.Context, division int, all bool) ([]*ManufacturingByProductReceipts, error) {
	var entities []*ManufacturingByProductReceipts
	u, err := s.client.ResolvePathWithDivision("/api/v1/{division}/manufacturing/ByProductReceipts?$select=*", division)
	if err != nil {
		return nil, err
	}
	if all {
		err = s.client.ListRequestAndDoAll(ctx, u.String(), &entities)
		return entities, err
	}
	_, _, _, err = s.client.ListRequestAndDo(ctx, u.String(), &entities)
	return entities, err
}
