// Copyright 2018 The go-exactonline AUTHORS. All rights reserved.
//
// Use of this source code is governed by a MIT
// license that can be found in the LICENSE file.
// Code generated by gen-services.go; DO NOT EDIT.
package exactonline

import (
	"context"
)

// ManufacturingWorkcentersService is responsible for communicating with
// the Workcenters endpoint of the Manufacturing service.
type ManufacturingWorkcentersService service

// ManufacturingWorkcenters:
// Service: Manufacturing
// Entity: Workcenters
// URL: /api/v1/{division}/manufacturing/Workcenters
// HasWebhook: false
// IsInBeta: false
// Methods: GET POST PUT DELETE
// Endpoint docs: https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=ManufacturingWorkcenters
type ManufacturingWorkcenters struct {
	// ID: Primary key
	ID *GUID `json:",omitempty"`

	// Capacity: Capacity of the work center
	Capacity *int `json:",omitempty"`

	// Code: Code of the work center
	Code *string `json:",omitempty"`

	// Costcenter: Reference to CostCenters
	Costcenter *string `json:",omitempty"`

	// CostcenterDescription: Description of Costcenter
	CostcenterDescription *string `json:",omitempty"`

	// Costunit: Reference to CostUnits
	Costunit *string `json:",omitempty"`

	// CostunitDescription: Description of Costunit
	CostunitDescription *string `json:",omitempty"`

	// Created: Creation date
	Created *Date `json:",omitempty"`

	// Creator: User ID of creator
	Creator *GUID `json:",omitempty"`

	// CreatorFullName: Name of creator
	CreatorFullName *string `json:",omitempty"`

	// Description: Description of the work center
	Description *string `json:",omitempty"`

	// Division: Division code
	Division *int `json:",omitempty"`

	// GeneralBurdenRate: General burden rate
	GeneralBurdenRate *float64 `json:",omitempty"`

	// IsLaborBurdenPercent: Indicates if labor burden is calculated as a percentage or amount
	IsLaborBurdenPercent *byte `json:",omitempty"`

	// LaborBurdenRate: Labor burden rate
	LaborBurdenRate *float64 `json:",omitempty"`

	// MachineBurdenRate: Machine burden rate
	MachineBurdenRate *float64 `json:",omitempty"`

	// Modified: Last modified date
	Modified *Date `json:",omitempty"`

	// Modifier: User ID of modifier
	Modifier *GUID `json:",omitempty"`

	// ModifierFullName: Name of modifier
	ModifierFullName *string `json:",omitempty"`

	// Notes: Remarks
	Notes *string `json:",omitempty"`

	// ProductionArea: Area to which the work center belongs.
	ProductionArea *GUID `json:",omitempty"`

	// RunLaborRate: Run labor rate
	RunLaborRate *float64 `json:",omitempty"`

	// SearchCode: Search code of the work center
	SearchCode *string `json:",omitempty"`

	// SetupLaborRate: Setup labor rate
	SetupLaborRate *float64 `json:",omitempty"`

	// Status: Reference to WorkcenterStatus
	Status *int `json:",omitempty"`

	// Type: Reference to WorkcenterTypes
	Type *int `json:",omitempty"`
}

func (s *ManufacturingWorkcenters) GetIdentifier() GUID {
	return *s.ID
}

// List the Workcenters entities in the provided divison.
// If all is true, all the paginated results are fetched; if false, list the first page.
func (s *ManufacturingWorkcentersService) List(ctx context.Context, division int, all bool) ([]*ManufacturingWorkcenters, error) {
	var entities []*ManufacturingWorkcenters
	u, err := s.client.ResolvePathWithDivision("/api/v1/{division}/manufacturing/Workcenters?$select=*", division)
	if err != nil {
		return nil, err
	}
	if all {
		err = s.client.ListRequestAndDoAll(ctx, u.String(), &entities)
		return entities, err
	}
	_, _, _, err = s.client.ListRequestAndDo(ctx, u.String(), &entities)
	return entities, err
}
