// Copyright 2018 The go-exactonline AUTHORS. All rights reserved.
//
// Use of this source code is governed by a MIT
// license that can be found in the LICENSE file.
// Code generated by gen-services.go; DO NOT EDIT.
package exactonline

import (
	"context"
)

// ProjectProjectRestrictionRebillingsService is responsible for communicating with
// the ProjectRestrictionRebillings endpoint of the Project service.
type ProjectProjectRestrictionRebillingsService service

// ProjectProjectRestrictionRebillings:
// Service: Project
// Entity: ProjectRestrictionRebillings
// URL: /api/v1/{division}/project/ProjectRestrictionRebillings
// HasWebhook: false
// IsInBeta: false
// Methods: GET POST PUT DELETE
// Endpoint docs: https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=ProjectProjectRestrictionRebillings
type ProjectProjectRestrictionRebillings struct {
	// ID: Primary key
	ID *GUID `json:"ID,omitempty"`

	// CostTypeRebill: Cost type reference
	CostTypeRebill *GUID `json:"CostTypeRebill,omitempty"`

	// CostTypeRebillCode: Cost type code
	CostTypeRebillCode *string `json:"CostTypeRebillCode,omitempty"`

	// CostTypeRebillDescription: Cost type description
	CostTypeRebillDescription *string `json:"CostTypeRebillDescription,omitempty"`

	// Created: Date created
	Created *Date `json:"Created,omitempty"`

	// Creator: Creator user ID
	Creator *GUID `json:"Creator,omitempty"`

	// CreatorFullName: Creator name
	CreatorFullName *string `json:"CreatorFullName,omitempty"`

	// Division: Division code
	Division *int `json:"Division,omitempty"`

	// Modified: Date modified
	Modified *Date `json:"Modified,omitempty"`

	// Modifier: Modifier user ID
	Modifier *GUID `json:"Modifier,omitempty"`

	// ModifierFullName: Modifier name
	ModifierFullName *string `json:"ModifierFullName,omitempty"`

	// Project: Project linked to the restriction
	Project *GUID `json:"Project,omitempty"`

	// ProjectCode: Project code
	ProjectCode *string `json:"ProjectCode,omitempty"`

	// ProjectDescription: Project description
	ProjectDescription *string `json:"ProjectDescription,omitempty"`
}

func (s *ProjectProjectRestrictionRebillings) GetIdentifier() GUID {
	return *s.ID
}

// List the ProjectRestrictionRebillings entities in the provided divison.
// If all is true, all the paginated results are fetched; if false, list the first page.
func (s *ProjectProjectRestrictionRebillingsService) List(ctx context.Context, division int, all bool) ([]*ProjectProjectRestrictionRebillings, error) {
	var entities []*ProjectProjectRestrictionRebillings
	u, err := s.client.ResolvePathWithDivision("/api/v1/{division}/project/ProjectRestrictionRebillings?$select=*", division)
	if err != nil {
		return nil, err
	}
	if all {
		err = s.client.ListRequestAndDoAll(ctx, u.String(), &entities)
		return entities, err
	}
	_, _, _, err = s.client.ListRequestAndDo(ctx, u.String(), &entities)
	return entities, err
}

/* // Get the ProjectRestrictionRebillings enitity, by ID.
func (s *ProjectProjectRestrictionRebillingsService) Get(ctx context.Context, division int, id GUID) (*ProjectProjectRestrictionRebillings, error) {
	var entities []*ProjectProjectRestrictionRebillings
	u, err := s.client.ResolvePathWithDivision("/api/v1/{division}/project/ProjectRestrictionRebillings?$select=*", division)
	if err != nil {
		return nil, err
	}

	if _, _, _, err := s.client.ListRequestAndDo(ctx, u.String(), &entities); err != nil {
		return nil, err
	}

	if len(entities) != 1 {
		return nil, fmt.Errorf("Returned %d ProjectRestrictionRebillings entities, expected 1", len(entities))
	}

	return entities[0], nil
} */
