// Copyright 2018 The go-exactonline AUTHORS. All rights reserved.
//
// Use of this source code is governed by a MIT
// license that can be found in the LICENSE file.
// Code generated by gen-services.go; DO NOT EDIT.
package exactonline

import (
	"context"
)

// ProjectTimeAndBillingEntryRecentActivitiesAndExpensesService is responsible for communicating with
// the TimeAndBillingEntryRecentActivitiesAndExpenses endpoint of the Project service.
type ProjectTimeAndBillingEntryRecentActivitiesAndExpensesService service

// ProjectTimeAndBillingEntryRecentActivitiesAndExpenses:
// Service: Project
// Entity: TimeAndBillingEntryRecentActivitiesAndExpenses
// URL: /api/v1/{division}/read/project/TimeAndBillingEntryRecentActivitiesAndExpenses
// HasWebhook: false
// IsInBeta: false
// Methods: GET
// Endpoint docs: https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=ReadProjectTimeAndBillingEntryRecentActivitiesAndExpenses
type ProjectTimeAndBillingEntryRecentActivitiesAndExpenses struct {
	// ID: Primary key
	ID *GUID `json:"ID,omitempty"`

	// DateLastUsed: Date last used
	DateLastUsed *Date `json:"DateLastUsed,omitempty"`

	// Description: Description
	Description *string `json:"Description,omitempty"`

	// ParentDescription: Description of Parent
	ParentDescription *string `json:"ParentDescription,omitempty"`
}

func (s *ProjectTimeAndBillingEntryRecentActivitiesAndExpenses) GetIdentifier() GUID {
	return *s.ID
}

// List the TimeAndBillingEntryRecentActivitiesAndExpenses entities in the provided divison.
// If all is true, all the paginated results are fetched; if false, list the first page.
func (s *ProjectTimeAndBillingEntryRecentActivitiesAndExpensesService) List(ctx context.Context, division int, all bool) ([]*ProjectTimeAndBillingEntryRecentActivitiesAndExpenses, error) {
	var entities []*ProjectTimeAndBillingEntryRecentActivitiesAndExpenses
	u, err := s.client.ResolvePathWithDivision("/api/v1/{division}/read/project/TimeAndBillingEntryRecentActivitiesAndExpenses?$select=*", division)
	if err != nil {
		return nil, err
	}
	if all {
		err = s.client.ListRequestAndDoAll(ctx, u.String(), &entities)
		return entities, err
	}
	_, _, _, err = s.client.ListRequestAndDo(ctx, u.String(), &entities)
	return entities, err
}

/* // Get the TimeAndBillingEntryRecentActivitiesAndExpenses enitity, by ID.
func (s *ProjectTimeAndBillingEntryRecentActivitiesAndExpensesService) Get(ctx context.Context, division int, id GUID) (*ProjectTimeAndBillingEntryRecentActivitiesAndExpenses, error) {
	var entities []*ProjectTimeAndBillingEntryRecentActivitiesAndExpenses
	u, err := s.client.ResolvePathWithDivision("/api/v1/{division}/read/project/TimeAndBillingEntryRecentActivitiesAndExpenses?$select=*", division)
	if err != nil {
		return nil, err
	}

	if _, _, _, err := s.client.ListRequestAndDo(ctx, u.String(), &entities); err != nil {
		return nil, err
	}

	if len(entities) != 1 {
		return nil, fmt.Errorf("Returned %d TimeAndBillingEntryRecentActivitiesAndExpenses entities, expected 1", len(entities))
	}

	return entities[0], nil
} */
