// Copyright 2018 The go-exactonline AUTHORS. All rights reserved.
//
// Use of this source code is governed by a MIT
// license that can be found in the LICENSE file.
// Code generated by gen-services.go; DO NOT EDIT.
package exactonline

import (
	"context"
)

// SalesInvoiceLayoutsService is responsible for communicating with
// the Layouts endpoint of the SalesInvoice service.
type SalesInvoiceLayoutsService service

// SalesInvoiceLayouts:
// Service: SalesInvoice
// Entity: Layouts
// URL: /api/v1/{division}/salesinvoice/Layouts
// HasWebhook: false
// IsInBeta: false
// Methods: GET
// Endpoint docs: https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=SalesInvoiceLayouts
type SalesInvoiceLayouts struct {
	// ID: Primary key
	ID *GUID `json:"ID,omitempty"`

	// Created: Creation date
	Created *Date `json:"Created,omitempty"`

	// Creator: User ID of the creator
	Creator *GUID `json:"Creator,omitempty"`

	// CreatorFullName: Name of the creator
	CreatorFullName *string `json:"CreatorFullName,omitempty"`

	// Division: Division code
	Division *int `json:"Division,omitempty"`

	// Modified: Last modified date
	Modified *Date `json:"Modified,omitempty"`

	// Modifier: User ID of the last modifier
	Modifier *GUID `json:"Modifier,omitempty"`

	// ModifierFullName: Name of the last modifier
	ModifierFullName *string `json:"ModifierFullName,omitempty"`

	// Subject: Layout name
	Subject *string `json:"Subject,omitempty"`

	// Type: Type: 1=Layout, 2=E-mail text layout, 3=Word template
	Type *int `json:"Type,omitempty"`
}

func (s *SalesInvoiceLayouts) GetIdentifier() GUID {
	return *s.ID
}

// List the Layouts entities in the provided divison.
// If all is true, all the paginated results are fetched; if false, list the first page.
func (s *SalesInvoiceLayoutsService) List(ctx context.Context, division int, all bool) ([]*SalesInvoiceLayouts, error) {
	var entities []*SalesInvoiceLayouts
	u, err := s.client.ResolvePathWithDivision("/api/v1/{division}/salesinvoice/Layouts?$select=*", division)
	if err != nil {
		return nil, err
	}
	if all {
		err = s.client.ListRequestAndDoAll(ctx, u.String(), &entities)
		return entities, err
	}
	_, _, _, err = s.client.ListRequestAndDo(ctx, u.String(), &entities)
	return entities, err
}

/* // Get the Layouts enitity, by ID.
func (s *SalesInvoiceLayoutsService) Get(ctx context.Context, division int, id GUID) (*SalesInvoiceLayouts, error) {
	var entities []*SalesInvoiceLayouts
	u, err := s.client.ResolvePathWithDivision("/api/v1/{division}/salesinvoice/Layouts?$select=*", division)
	if err != nil {
		return nil, err
	}

	if _, _, _, err := s.client.ListRequestAndDo(ctx, u.String(), &entities); err != nil {
		return nil, err
	}

	if len(entities) != 1 {
		return nil, fmt.Errorf("Returned %d Layouts entities, expected 1", len(entities))
	}

	return entities[0], nil
} */
