// Copyright 2018 The go-exactonline AUTHORS. All rights reserved.
//
// Use of this source code is governed by a MIT
// license that can be found in the LICENSE file.
// Code generated by gen-services.go; DO NOT EDIT.
package exactonline

import (
	"context"
)

// SalesOrderGoodsDeliveryLinesService is responsible for communicating with
// the GoodsDeliveryLines endpoint of the SalesOrder service.
type SalesOrderGoodsDeliveryLinesService service

// SalesOrderGoodsDeliveryLines:
// Service: SalesOrder
// Entity: GoodsDeliveryLines
// URL: /api/v1/{division}/salesorder/GoodsDeliveryLines
// HasWebhook: true
// IsInBeta: false
// Methods: GET POST PUT
// Endpoint docs: https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=SalesOrderGoodsDeliveryLines
type SalesOrderGoodsDeliveryLines struct {
	// ID:
	ID *GUID `json:"ID,omitempty"`

	// BatchNumbers:
	BatchNumbers *[]byte `json:"BatchNumbers,omitempty"`

	// Created:
	Created *Date `json:"Created,omitempty"`

	// Creator:
	Creator *GUID `json:"Creator,omitempty"`

	// CreatorFullName:
	CreatorFullName *string `json:"CreatorFullName,omitempty"`

	// DeliveryDate:
	DeliveryDate *Date `json:"DeliveryDate,omitempty"`

	// Description:
	Description *string `json:"Description,omitempty"`

	// Division:
	Division *int `json:"Division,omitempty"`

	// EntryID:
	EntryID *GUID `json:"EntryID,omitempty"`

	// Item:
	Item *GUID `json:"Item,omitempty"`

	// ItemCode:
	ItemCode *string `json:"ItemCode,omitempty"`

	// ItemDescription:
	ItemDescription *string `json:"ItemDescription,omitempty"`

	// LineNumber:
	LineNumber *int `json:"LineNumber,omitempty"`

	// Modified:
	Modified *Date `json:"Modified,omitempty"`

	// Modifier:
	Modifier *GUID `json:"Modifier,omitempty"`

	// ModifierFullName:
	ModifierFullName *string `json:"ModifierFullName,omitempty"`

	// Notes:
	Notes *string `json:"Notes,omitempty"`

	// QuantityDelivered:
	QuantityDelivered *float64 `json:"QuantityDelivered,omitempty"`

	// QuantityOrdered:
	QuantityOrdered *float64 `json:"QuantityOrdered,omitempty"`

	// SalesOrderLineID:
	SalesOrderLineID *GUID `json:"SalesOrderLineID,omitempty"`

	// SalesOrderLineNumber:
	SalesOrderLineNumber *int `json:"SalesOrderLineNumber,omitempty"`

	// SalesOrderNumber:
	SalesOrderNumber *int `json:"SalesOrderNumber,omitempty"`

	// SerialNumbers:
	SerialNumbers *[]byte `json:"SerialNumbers,omitempty"`

	// StorageLocation:
	StorageLocation *GUID `json:"StorageLocation,omitempty"`

	// StorageLocationCode:
	StorageLocationCode *string `json:"StorageLocationCode,omitempty"`

	// StorageLocationDescription:
	StorageLocationDescription *string `json:"StorageLocationDescription,omitempty"`

	// TrackingNumber:
	TrackingNumber *string `json:"TrackingNumber,omitempty"`

	// Unitcode:
	Unitcode *string `json:"Unitcode,omitempty"`
}

func (s *SalesOrderGoodsDeliveryLines) GetIdentifier() GUID {
	return *s.ID
}

// List the GoodsDeliveryLines entities in the provided divison.
// If all is true, all the paginated results are fetched; if false, list the first page.
func (s *SalesOrderGoodsDeliveryLinesService) List(ctx context.Context, division int, all bool) ([]*SalesOrderGoodsDeliveryLines, error) {
	var entities []*SalesOrderGoodsDeliveryLines
	u, err := s.client.ResolvePathWithDivision("/api/v1/{division}/salesorder/GoodsDeliveryLines?$select=*", division)
	if err != nil {
		return nil, err
	}
	if all {
		err = s.client.ListRequestAndDoAll(ctx, u.String(), &entities)
		return entities, err
	}
	_, _, _, err = s.client.ListRequestAndDo(ctx, u.String(), &entities)
	return entities, err
}

/* // Get the GoodsDeliveryLines enitity, by ID.
func (s *SalesOrderGoodsDeliveryLinesService) Get(ctx context.Context, division int, id GUID) (*SalesOrderGoodsDeliveryLines, error) {
	var entities []*SalesOrderGoodsDeliveryLines
	u, err := s.client.ResolvePathWithDivision("/api/v1/{division}/salesorder/GoodsDeliveryLines?$select=*", division)
	if err != nil {
		return nil, err
	}

	if _, _, _, err := s.client.ListRequestAndDo(ctx, u.String(), &entities); err != nil {
		return nil, err
	}

	if len(entities) != 1 {
		return nil, fmt.Errorf("Returned %d GoodsDeliveryLines entities, expected 1", len(entities))
	}

	return entities[0], nil
} */
