// Copyright 2018 The go-exactonline AUTHORS. All rights reserved.
//
// Use of this source code is governed by a MIT
// license that can be found in the LICENSE file.
// Code generated by gen-services.go; DO NOT EDIT.
package exactonline

import (
	"context"
)

// SubscriptionSubscriptionLineTypesService is responsible for communicating with
// the SubscriptionLineTypes endpoint of the Subscription service.
type SubscriptionSubscriptionLineTypesService service

// SubscriptionSubscriptionLineTypes:
// Service: Subscription
// Entity: SubscriptionLineTypes
// URL: /api/v1/{division}/subscription/SubscriptionLineTypes
// HasWebhook: false
// IsInBeta: false
// Methods: GET
// Endpoint docs: https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=SubscriptionSubscriptionLineTypes
type SubscriptionSubscriptionLineTypes struct {
	// ID: Primary key
	ID *int `json:",omitempty"`

	// Description: Description
	Description *string `json:",omitempty"`
}

func (s *SubscriptionSubscriptionLineTypes) GetIdentifier() int {
	return *s.ID
}

// List the SubscriptionLineTypes entities in the provided divison.
// If all is true, all the paginated results are fetched; if false, list the first page.
func (s *SubscriptionSubscriptionLineTypesService) List(ctx context.Context, division int, all bool) ([]*SubscriptionSubscriptionLineTypes, error) {
	var entities []*SubscriptionSubscriptionLineTypes
	u, err := s.client.ResolvePathWithDivision("/api/v1/{division}/subscription/SubscriptionLineTypes?$select=*", division)
	if err != nil {
		return nil, err
	}
	if all {
		err = s.client.ListRequestAndDoAll(ctx, u.String(), &entities)
		return entities, err
	}
	_, _, _, err = s.client.ListRequestAndDo(ctx, u.String(), &entities)
	return entities, err
}
