// Copyright 2018 The go-exactonline AUTHORS. All rights reserved.
//
// Use of this source code is governed by a MIT
// license that can be found in the LICENSE file.
// Code generated by gen-services.go; DO NOT EDIT.
package manufacturing

import (
	"context"
	"fmt"
	"io/ioutil"
	"net/http"

	"github.com/mcnijman/go-exactonline/api"
	"github.com/mcnijman/go-exactonline/types"
)

// OperationResourcesEndpoint is responsible for communicating with
// the OperationResources endpoint of the Manufacturing service.
type OperationResourcesEndpoint service

// OperationResources:
// Service: Manufacturing
// Entity: OperationResources
// URL: /api/v1/{division}/manufacturing/OperationResources
// HasWebhook: false
// IsInBeta: false
// Methods: GET POST PUT DELETE
// Endpoint docs: https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=ManufacturingOperationResources
type OperationResources struct {
	MetaData *api.MetaData `json:"__metadata,omitempty"`
	// ID: Primary key
	ID *types.GUID `json:"ID,omitempty"`

	// Account: Reference to Accounts
	Account *types.GUID `json:"Account,omitempty"`

	// AttendedPercentage: Attended percentage
	AttendedPercentage *float64 `json:"AttendedPercentage,omitempty"`

	// Created: Creation date
	Created *types.Date `json:"Created,omitempty"`

	// Creator: User ID of creator
	Creator *types.GUID `json:"Creator,omitempty"`

	// CreatorFullName: Name of creator
	CreatorFullName *string `json:"CreatorFullName,omitempty"`

	// Currency: Reference to Currencies
	Currency *string `json:"Currency,omitempty"`

	// Division: Division code
	Division *int `json:"Division,omitempty"`

	// EfficiencyPercentage: Efficiency percentage
	EfficiencyPercentage *float64 `json:"EfficiencyPercentage,omitempty"`

	// IsPrimary: Indicates if this is the primary operation of the workcenter
	IsPrimary *byte `json:"IsPrimary,omitempty"`

	// Modified: Last modified date
	Modified *types.Date `json:"Modified,omitempty"`

	// Modifier: User ID of modifier
	Modifier *types.GUID `json:"Modifier,omitempty"`

	// ModifierFullName: Name of modifier
	ModifierFullName *string `json:"ModifierFullName,omitempty"`

	// Operation: Reference to Operations
	Operation *types.GUID `json:"Operation,omitempty"`

	// OperationDescription: Description of Operation
	OperationDescription *string `json:"OperationDescription,omitempty"`

	// PurchaseLeadDays: Lead days from purchase
	PurchaseLeadDays *int `json:"PurchaseLeadDays,omitempty"`

	// PurchaseUnit: Unit of purchased item from supplier
	PurchaseUnit *string `json:"PurchaseUnit,omitempty"`

	// PurchaseVATCode: VAT code used for purchased item from supplier
	PurchaseVATCode *string `json:"PurchaseVATCode,omitempty"`

	// Run: Used in conjuction with RunMethod and EfficiencyPercentage to determine PlannedRunHours
	Run *float64 `json:"Run,omitempty"`

	// RunMethod: Reference to OperationRunMethods
	RunMethod *int `json:"RunMethod,omitempty"`

	// Setup: Used in conjunction with SetupCount and SetupUnit to determine PlannedSetupHours
	Setup *float64 `json:"Setup,omitempty"`

	// SetupUnit: Reference to TimeUnits
	SetupUnit *string `json:"SetupUnit,omitempty"`

	// Type: Reference to RoutingStepTypes
	Type *int `json:"Type,omitempty"`

	// Workcenter: Reference to Workcenter
	Workcenter *types.GUID `json:"Workcenter,omitempty"`

	// WorkcenterDescription: Description of Workcenter
	WorkcenterDescription *string `json:"WorkcenterDescription,omitempty"`
}

func (e *OperationResources) GetPrimary() *types.GUID {
	return e.ID
}

func (s *OperationResourcesEndpoint) UserHasRights(ctx context.Context, division int, method string) (bool, error) {
	return s.client.UserHasRights(ctx, division, "manufacturing/OperationResources", method)
}

// List the OperationResources entities in the provided division.
// If all is true, all the paginated results are fetched; if false, list the first page.
func (s *OperationResourcesEndpoint) List(ctx context.Context, division int, all bool, o *api.ListOptions) ([]*OperationResources, error) {
	var entities []*OperationResources
	u, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/manufacturing/OperationResources", division) // #nosec
	api.AddListOptionsToURL(u, o)

	if all {
		err := s.client.ListRequestAndDoAll(ctx, u.String(), &entities)
		return entities, err
	}
	_, _, err := s.client.NewRequestAndDo(ctx, "GET", u.String(), nil, &entities)
	return entities, err
}

// Get the OperationResources entitiy in the provided division.
func (s *OperationResourcesEndpoint) Get(ctx context.Context, division int, id *types.GUID) (*OperationResources, error) {
	b, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/manufacturing/OperationResources", division) // #nosec
	u, err := api.AddOdataKeyToURL(b, id)
	if err != nil {
		return nil, err
	}

	e := &OperationResources{}
	_, _, requestError := s.client.NewRequestAndDo(ctx, "GET", u.String(), nil, e)
	return e, requestError
}

// New returns an empty OperationResources entity
func (s *OperationResourcesEndpoint) New() *OperationResources {
	return &OperationResources{}
}

// Create the OperationResources entity in the provided division.
func (s *OperationResourcesEndpoint) Create(ctx context.Context, division int, entity *OperationResources) (*OperationResources, error) {
	u, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/manufacturing/OperationResources", division) // #nosec
	e := &OperationResources{}
	_, _, err := s.client.NewRequestAndDo(ctx, "POST", u.String(), entity, e)
	if err != nil {
		return nil, err
	}
	return e, nil
}

// Update the OperationResources entity in the provided division.
func (s *OperationResourcesEndpoint) Update(ctx context.Context, division int, entity *OperationResources) (*OperationResources, error) {
	b, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/manufacturing/OperationResources", division) // #nosec
	u, err := api.AddOdataKeyToURL(b, entity.GetPrimary())
	if err != nil {
		return nil, err
	}

	e := &OperationResources{}
	_, _, requestError := s.client.NewRequestAndDo(ctx, "PUT", u.String(), entity, e)
	return e, requestError
}

// Delete the OperationResources entity in the provided division.
func (s *OperationResourcesEndpoint) Delete(ctx context.Context, division int, id *types.GUID) error {
	b, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/manufacturing/OperationResources", division) // #nosec
	u, err := api.AddOdataKeyToURL(b, id)
	if err != nil {
		return err
	}

	_, r, requestError := s.client.NewRequestAndDo(ctx, "DELETE", u.String(), nil, nil)
	if requestError != nil {
		return requestError
	}

	if r.StatusCode != http.StatusNoContent {
		body, _ := ioutil.ReadAll(r.Body) // #nosec
		return fmt.Errorf("Failed with status %v and body %v", r.StatusCode, body)
	}

	return nil
}
