// Copyright 2018 The go-exactonline AUTHORS. All rights reserved.
//
// Use of this source code is governed by a MIT
// license that can be found in the LICENSE file.
// Code generated by gen-services.go; DO NOT EDIT.
package project

import (
	"context"

	"github.com/mcnijman/go-exactonline/types"
)

// TimeCorrectionsEndpoint is responsible for communicating with
// the TimeCorrections endpoint of the Project service.
type TimeCorrectionsEndpoint service

// TimeCorrections:
// Service: Project
// Entity: TimeCorrections
// URL: /api/v1/{division}/project/TimeCorrections
// HasWebhook: false
// IsInBeta: false
// Methods: GET POST PUT DELETE
// Endpoint docs: https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=ProjectTimeCorrections
type TimeCorrections struct {
	// ID: Id
	ID *types.GUID `json:"ID,omitempty"`

	// Created: Creation date
	Created *types.Date `json:"Created,omitempty"`

	// Creator: User ID of creator
	Creator *types.GUID `json:"Creator,omitempty"`

	// CreatorFullName: Name of creator
	CreatorFullName *string `json:"CreatorFullName,omitempty"`

	// Division: Division code
	Division *int `json:"Division,omitempty"`

	// Modified: Last modified date
	Modified *types.Date `json:"Modified,omitempty"`

	// Modifier: User ID of modifier
	Modifier *types.GUID `json:"Modifier,omitempty"`

	// ModifierFullName: Name of modifier
	ModifierFullName *string `json:"ModifierFullName,omitempty"`

	// Notes: Notes
	Notes *string `json:"Notes,omitempty"`

	// OriginalEntryId: Reference to the time entry that this corrects for
	OriginalEntryId *types.GUID `json:"OriginalEntryId,omitempty"`

	// Quantity: Quantity has to be negative value. E.g.: If original quantity is 10 and the correct quantity is 4, this quantity is -6
	Quantity *float64 `json:"Quantity,omitempty"`
}

// List the TimeCorrections entities in the provided division.
// If all is true, all the paginated results are fetched; if false, list the first page.
func (s *TimeCorrectionsEndpoint) List(ctx context.Context, division int, all bool) ([]*TimeCorrections, error) {
	var entities []*TimeCorrections
	u, err := s.client.ResolvePathWithDivision("/api/v1/{division}/project/TimeCorrections?$select=*", division)
	if err != nil {
		return nil, err
	}
	if all {
		err = s.client.ListRequestAndDoAll(ctx, u.String(), &entities)
		return entities, err
	}
	_, _, _, err = s.client.ListRequestAndDo(ctx, u.String(), &entities)
	return entities, err
}
