// Copyright 2018 The go-exactonline AUTHORS. All rights reserved.
//
// Use of this source code is governed by a MIT
// license that can be found in the LICENSE file.
// Code generated by gen-services.go; DO NOT EDIT.
package workflow

import "github.com/mcnijman/go-exactonline/api"

type service struct {
	client *api.Client
}

// WorkflowService is responsible for communication with the Workflow
// endpoints of the Exact Online API.
type WorkflowService struct {
	client *api.Client

	common service // Reuse a single struct instead of allocating one for each service on the heap.

	// Endpoints available under this service
	RequestAttachments *RequestAttachmentsEndpoint
}

// NewWorkflowService creates a new initialized instance of the
// WorkflowService.
func NewWorkflowService(apiClient *api.Client) *WorkflowService {
	s := &WorkflowService{client: apiClient}

	s.common.client = apiClient

	s.RequestAttachments = (*RequestAttachmentsEndpoint)(&s.common)

	return s
}
