// Copyright 2018 The go-exactonline AUTHORS. All rights reserved.
//
// Use of this source code is governed by a MIT
// license that can be found in the LICENSE file.
// Code generated by gen-services.go; DO NOT EDIT.
package assets

import (
	"context"

	"github.com/mcnijman/go-exactonline/api"
	"github.com/mcnijman/go-exactonline/types"
)

// AssetsEndpoint is responsible for communicating with
// the Assets endpoint of the Assets service.
type AssetsEndpoint service

// Assets:
// Service: Assets
// Entity: Assets
// URL: /api/v1/{division}/assets/Assets
// HasWebhook: false
// IsInBeta: false
// Methods: GET
// Endpoint docs: https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=AssetsAssets
type Assets struct {
	MetaData *api.MetaData `json:"__metadata,omitempty"`
	// ID: Primary key
	ID *types.GUID `json:"ID,omitempty"`

	// AlreadyDepreciated: Indicates if an asset was already depreciated before registering it in Exact Online
	AlreadyDepreciated *byte `json:"AlreadyDepreciated,omitempty"`

	// AssetFrom: In case of a transfer or a split, the original asset ID is saved in this field. This is done to provide tracability of the Asset
	AssetFrom *types.GUID `json:"AssetFrom,omitempty"`

	// AssetFromDescription: Description of AssetFrom
	AssetFromDescription *string `json:"AssetFromDescription,omitempty"`

	// AssetGroup: Asset group identifies GLAccounts to be used for Asset transactions
	AssetGroup *types.GUID `json:"AssetGroup,omitempty"`

	// AssetGroupCode: Code of the asset group
	AssetGroupCode *string `json:"AssetGroupCode,omitempty"`

	// AssetGroupDescription: Description of the asset group
	AssetGroupDescription *string `json:"AssetGroupDescription,omitempty"`

	// CatalogueValue: The catalogue value of the asset
	CatalogueValue *float64 `json:"CatalogueValue,omitempty"`

	// Code: Code of the asset
	Code *string `json:"Code,omitempty"`

	// Costcenter: Assets can be linked to a cost center
	Costcenter *string `json:"Costcenter,omitempty"`

	// CostcenterDescription: Description of Costcenter
	CostcenterDescription *string `json:"CostcenterDescription,omitempty"`

	// Costunit: Assets can be linked to a cost unit
	Costunit *string `json:"Costunit,omitempty"`

	// CostunitDescription: Description of Costunit
	CostunitDescription *string `json:"CostunitDescription,omitempty"`

	// Created: Creation date
	Created *types.Date `json:"Created,omitempty"`

	// Creator: User ID of creator
	Creator *types.GUID `json:"Creator,omitempty"`

	// CreatorFullName: Name of creator
	CreatorFullName *string `json:"CreatorFullName,omitempty"`

	// DeductionPercentage: Used for Belgium legislation. Used to produce the official &#39;Investment deduction&#39; report
	DeductionPercentage *float64 `json:"DeductionPercentage,omitempty"`

	// DepreciatedAmount: Amount that is already depreciated when adding an existing asset. Can only be filled when &#39;Alreadydepreciated&#39; is on
	DepreciatedAmount *float64 `json:"DepreciatedAmount,omitempty"`

	// DepreciatedPeriods: Number of periods that already have been depreciated for the asset. Can only be filled when &#39;Alreadydepreciated&#39; is on
	DepreciatedPeriods *int `json:"DepreciatedPeriods,omitempty"`

	// DepreciatedStartDate: StartDate of depreciating. Can only be filled when &#39;Alreadydepreciated&#39; is on
	DepreciatedStartDate *types.Date `json:"DepreciatedStartDate,omitempty"`

	// Description: This is the description of the Asset
	Description *string `json:"Description,omitempty"`

	// Division: Division code
	Division *int `json:"Division,omitempty"`

	// EndDate: Asset EndDate is filled when asset is Sold or Inactive
	EndDate *types.Date `json:"EndDate,omitempty"`

	// EngineEmission: Engine emission of the asset, needed to calculate the co² report
	EngineEmission *int `json:"EngineEmission,omitempty"`

	// EngineType: Engine type of the asset, Needed to generate a co² report
	EngineType *int `json:"EngineType,omitempty"`

	// GLTransactionLine: Links to the gltransactions.id. GL transaction line based on which the asset is created
	GLTransactionLine *types.GUID `json:"GLTransactionLine,omitempty"`

	// GLTransactionLineDescription: Description of GLTransactionLine
	GLTransactionLineDescription *string `json:"GLTransactionLineDescription,omitempty"`

	// InvestmentAccount: Supplier of the asset
	InvestmentAccount *types.GUID `json:"InvestmentAccount,omitempty"`

	// InvestmentAccountCode: Code of InvestmentAccount
	InvestmentAccountCode *string `json:"InvestmentAccountCode,omitempty"`

	// InvestmentAccountName: Name of InvestmentAccount
	InvestmentAccountName *string `json:"InvestmentAccountName,omitempty"`

	// InvestmentAmountDC: Investment amount in the default currency of the company
	InvestmentAmountDC *float64 `json:"InvestmentAmountDC,omitempty"`

	// InvestmentAmountFC: Investment value of the asset. Currently the field is filled with the PurchasePriceLocal. Can be status &#39;Not used&#39; after sources have been cleaned
	InvestmentAmountFC *float64 `json:"InvestmentAmountFC,omitempty"`

	// InvestmentCurrency: Indicates the currency of the investment amount
	InvestmentCurrency *string `json:"InvestmentCurrency,omitempty"`

	// InvestmentCurrencyDescription: Description of InvestmentCurrency
	InvestmentCurrencyDescription *string `json:"InvestmentCurrencyDescription,omitempty"`

	// InvestmentDate: Refers to the original date when the asset was bought
	InvestmentDate *types.Date `json:"InvestmentDate,omitempty"`

	// InvestmentDeduction: Belgian functionality, to determine how a local legal report regarding investment deduction must be created
	InvestmentDeduction *int `json:"InvestmentDeduction,omitempty"`

	// Modified: Last modified date
	Modified *types.Date `json:"Modified,omitempty"`

	// Modifier: User ID of modifier
	Modifier *types.GUID `json:"Modifier,omitempty"`

	// ModifierFullName: Name of modifier
	ModifierFullName *string `json:"ModifierFullName,omitempty"`

	// Notes: Extra remarks for the asset
	Notes *string `json:"Notes,omitempty"`

	// Parent: Parent asset
	Parent *types.GUID `json:"Parent,omitempty"`

	// ParentCode: Code of Parent
	ParentCode *string `json:"ParentCode,omitempty"`

	// ParentDescription: Description of Parent
	ParentDescription *string `json:"ParentDescription,omitempty"`

	// Picture: Image for an asset
	Picture *[]byte `json:"Picture,omitempty"`

	// PictureFileName: Filename of the image
	PictureFileName *string `json:"PictureFileName,omitempty"`

	// PrimaryMethod: First method of depreciation. Currently, it is the only one used
	PrimaryMethod *types.GUID `json:"PrimaryMethod,omitempty"`

	// PrimaryMethodCode: Code of PrimaryMethod
	PrimaryMethodCode *string `json:"PrimaryMethodCode,omitempty"`

	// PrimaryMethodDescription: Description of PrimaryMethod
	PrimaryMethodDescription *string `json:"PrimaryMethodDescription,omitempty"`

	// ResidualValue: Indicates the residual value of the asset at the end of the depreciation
	ResidualValue *float64 `json:"ResidualValue,omitempty"`

	// StartDate: Asset Depreciation StartDate
	StartDate *types.Date `json:"StartDate,omitempty"`

	// Status: Identifies the status of the Asset. (see AssetStatus table to see the possibilities)
	Status *int `json:"Status,omitempty"`

	// TransactionEntryID: Reference to the transaction lines that make up the financial entry.
	TransactionEntryID *types.GUID `json:"TransactionEntryID,omitempty"`

	// TransactionEntryNo: Entry number of transaction
	TransactionEntryNo *int `json:"TransactionEntryNo,omitempty"`
}

func (e *Assets) GetPrimary() *types.GUID {
	return e.ID
}

func (s *AssetsEndpoint) UserHasRights(ctx context.Context, division int, method string) (bool, error) {
	return s.client.UserHasRights(ctx, division, "assets/Assets", method)
}

// List the Assets entities in the provided division.
// If all is true, all the paginated results are fetched; if false, list the first page.
func (s *AssetsEndpoint) List(ctx context.Context, division int, all bool, o *api.ListOptions) ([]*Assets, error) {
	var entities []*Assets
	u, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/assets/Assets", division) // #nosec
	api.AddListOptionsToURL(u, o)

	if all {
		err := s.client.ListRequestAndDoAll(ctx, u.String(), &entities)
		return entities, err
	}
	_, _, err := s.client.NewRequestAndDo(ctx, "GET", u.String(), nil, &entities)
	return entities, err
}

// Get the Assets entitiy in the provided division.
func (s *AssetsEndpoint) Get(ctx context.Context, division int, id *types.GUID) (*Assets, error) {
	b, _ := s.client.ResolvePathWithDivision("/api/v1/{division}/assets/Assets", division) // #nosec
	u, err := api.AddOdataKeyToURL(b, id)
	if err != nil {
		return nil, err
	}

	e := &Assets{}
	_, _, requestError := s.client.NewRequestAndDo(ctx, "GET", u.String(), nil, e)
	return e, requestError
}
